runtime: python311
instance_class: B2

entrypoint: uvicorn main:app --host=0.0.0.0 --port=$PORT

basic_scaling:
  max_instances: 2
  idle_timeout: 10m

env_variables:
  MONGO_URL: mongodb+srv://sheep5168947:K3gELDD3DalG3quO@cluster0.s55hmhg.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
